# examples/feature_first_example/analysis_options.yaml

analyzer:
  plugins:
    # This enables the custom_lint engine
    - custom_lint

custom_lint:
  # This tells custom_lint to look for rules in your local package
  # (Assuming architecture_lints is in your dev_dependencies)
  debug: true

  # If you wanted to DISABLE a specific rule, you would do this:
  rules:
    - arch_orphan_file: true

    - arch_naming_pattern: false
    - arch_naming_antipattern: false

    - arch_dep_layer: false
    - arch_dep_external: false

    - arch_type_missing_base: true
    - arch_type_strict: true
    - arch_type_forbidden: true


